version: 0.2

env:
  variables:
    S3_BUCKET: "xgc-content"
    S3_KEY: "library_check"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing dependencies..."
      - mkdir -p python_dependencies/python
      - pip install -r requirements.txt -t python_dependencies/python/

  pre_build:
    commands:
      - echo "Starting build phase..."
      - echo "Checking directory structure..."
      - ls -la python_dependencies/python/
      
  build:
    commands:
      - echo "Creating zip from python_dependencies folder..."
      - cd python_dependencies
      - zip -r9 ../python_dependencies.zip .
      - cd ..
      - echo "Uploading zip file to S3..."
      - aws s3 cp python_dependencies.zip s3://${S3_BUCKET}/${S3_KEY}/python_dependencies.zip
      - echo "Build completed successfully!"

artifacts:
  files:
    - python_dependencies.zip
  name: python-dependencies-$(date +%Y-%m-%d)
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip'
    - 'python_dependencies/**/*'